apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ay82qmhgo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ay82qmhgo-python 
  name: ay82qmhgo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ay82qmhgo-python 
